---
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false
  become: true
  tags:
    - load_balancers

  roles:
    - role: firewall
      vars:
        firewall_services:
          - http
        firewall_tcp_ports:
          - 80

#    - role: haproxy
